### ISSUE TITLE
difference between LFBO(pi) and BORE

### ISSUE THREAD

**Issue by zhanglei1172** [lfbo-ml/lfbo#1]
![image](https://user-images.githubusercontent.com/34906782/177021975-af7ed99b-2fcb-43a5-a297-04e82a51d0e1.png)

I noticed that the LFBO (PI) approximation error is smaller than the bore approximation in the results specifically compared with BORE in the paper. But isn't the pi version of LFBO the same as bore? Why are there differences?

**Comment by jiamings** [comment]
There is a small difference between LFBO (PI) and BORE.
- In BORE, the points over the threshold will only have the positive label.
- In LFBO, the points above the threshold has both positive and negative labels. 
So one measures p(x) / q(x) and the other measures p(x) / (p(x) + q(x)), where p(x) is distribution of x where y = 1 and q(x) the one where y = 0.
